mysql_dir: /home/data
# mysql_basedir = mysql_dir / mysql
mysql_basedir: /home/data/mysql
mysql_datadir: /data
mysql_user: mysql
mysql_database_user: root
mysql_passwd: 'root'
mysql_port: 3306
# mysql_sock = mysql_datadir / mysql.sock
mysql_sock: /data/mysql.sock
mysql_charset: utf8
mysql_collation: utf8_general_ci
#mysql_version: mysql-5.6.22-linux-glibc2.5-x86_64
#mysql_version: mysql-5.6.31-linux-glibc2.5-x86_64
mysql_version: mysql-5.7.14-linux-glibc2.5-x86_64
